git check files

diff --git a/.github/workflows/airflow_server.yml b/.github/workflows/airflow_server.yml
--- a/.github/workflows/airflow_server.yml
+++ b/.github/workflows/airflow_server.yml
@@ -32,6 +32,12 @@ jobs:
         run: |
           echo "EC2_PUBLIC_IP from GITHUB_ENV: ${{ env.EC2_PUBLIC_IP }}"
 
+      - name: Check Files for SCP
+        run: |
+          echo "Checking files for SCP..."
+          ls -l ./docker-compose.yml
+          ls -l ./config || echo "Config directory not found"
+
       - name: Upload docker-compose.yml to EC2
         uses: appleboy/scp-action@v0.1.1
         with:
