add ssh

diff --git a/.github/workflows/airflow_server.yml b/.github/workflows/airflow_server.yml
--- a/.github/workflows/airflow_server.yml
+++ b/.github/workflows/airflow_server.yml
@@ -42,7 +42,7 @@ jobs:
         run: |
           echo "Checking files for SCP..."
           ls -l ./docker-compose.yml
-          ls -l ./config/ || echo "Config directory not found"
+          ls -l ./config || echo "Config directory not found"
 
       - name: Upload docker-compose.yml to EC2
         uses: appleboy/scp-action@v0.1.1
