add missing directories

diff --git a/.github/workflows/airflow_server.yml b/.github/workflows/airflow_server.yml
--- a/.github/workflows/airflow_server.yml
+++ b/.github/workflows/airflow_server.yml
@@ -32,11 +32,17 @@ jobs:
         run: |
           echo "EC2_PUBLIC_IP from GITHUB_ENV: ${{ env.EC2_PUBLIC_IP }}"
 
+      - name: Ensure Required Directories Exist
+        run: |
+          mkdir -p logs dags data config plugins tests
+          echo "Directories created or already exist"
+
+
       - name: Check Files for SCP
         run: |
           echo "Checking files for SCP..."
           ls -l ./docker-compose.yml
-          ls -l ./config || echo "Config directory not found"
+          ls -l ./config/ || echo "Config directory not found"
 
       - name: Upload docker-compose.yml to EC2
         uses: appleboy/scp-action@v0.1.1
